version: '3.8'
services:
  core_api:
    container_name: core_api_app
    build: .
    image: ghcr.io/leehu-123/core-api:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin:secretpassword@postgres_db:5432/warehouse_db?schema=public
      - NODE_ENV=production
      - JWT_SECRET=dafa-warehouse-secret-key-2024
      - TELEGRAM_BOT_TOKEN=8878436482:AAFKlyhW8qDq7YGtULZO9LkiPZLEzMf8IGU
      - WAREHOUSE_APP_URL=https://warehouse.ldhuy.name.vn
    ports:
      - "4000:3003"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app_network
networks:
  app_network:
    external: true
