version: '3.8'
services:
  core_api:
    build: .
    container_name: core_api_app
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin:secretpassword@postgres_db:5432/warehouse_db?schema=public
      - NODE_ENV=production
      - JWT_SECRET=dafa-warehouse-secret-key-2024
    ports:
      - "4000:3003"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app_network
networks:
  app_network:
    external: true
